# Generated by Django 4.2.21 on 2025-05-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
