# Generated by Django 4.2.21 on 2025-05-22 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_main', '0002_forumpost_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
